// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtq9lgvFolDYTmWJgPK6SsD08vUH4eKdM',
    appId: '1:466569446594:web:c298f1d1b7b4570146a75b',
    messagingSenderId: '466569446594',
    projectId: 'app-neeicum',
    authDomain: 'app-neeicum.firebaseapp.com',
    databaseURL: 'https://app-neeicum-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-neeicum.appspot.com',
    measurementId: 'G-MZ4WXM0Z0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwrOeB8o_psr_jEcC2HEsJTsAmLXs304E',
    appId: '1:466569446594:android:e41984ec538e41b746a75b',
    messagingSenderId: '466569446594',
    projectId: 'app-neeicum',
    databaseURL: 'https://app-neeicum-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-neeicum.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs8W7UTvN8O5oKfSXID-zbF14EoKwYcvY',
    appId: '1:466569446594:ios:614847fbee6428a246a75b',
    messagingSenderId: '466569446594',
    projectId: 'app-neeicum',
    databaseURL: 'https://app-neeicum-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-neeicum.appspot.com',
    iosClientId: '466569446594-07sq8upu7ldtsed405p1o17ac7pqkvvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.neeicum',
  );
}
